export const LOAD_USER_DATA = Symbol('LOAD_USER_DATA');
export const LOAD_USER_RESOURCE_FILTER = Symbol('LOAD_USER_RESOURCE_FILTER');
export const LOAD_USER_GROUP_FILTER = Symbol('LOAD_USER_GROUP_FILTER');
export const LOAD_USER_ROLE_FILTER = Symbol('LOAD_USER_ROLE_FILTER');
export const LOAD_USER_LIST = Symbol('LOAD_USER_LIST');
export const LOAD_USER_PAGINATION = Symbol('LOAD_USER_PAGINATION');
